// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/favourites/data/models/favourite_movie.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3236871751281310736),
    name: 'FavouriteMovie',
    lastPropertyId: const obx_int.IdUid(10, 7482111380617275985),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6773887426627622703),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6500788782033594538),
        name: 'movieId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 2637413998594094171),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1224246652212309848),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3622965264758860134),
        name: 'overview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8971813696866806501),
        name: 'posterPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1212252746137319530),
        name: 'backdropPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3607501100080522108),
        name: 'releaseDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4904228441083503299),
        name: 'voteAverage',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1296287325628786633),
        name: 'voteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7482111380617275985),
        name: 'savedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3236871751281310736),
    lastIndexId: const obx_int.IdUid(1, 2637413998594094171),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FavouriteMovie: obx_int.EntityDefinition<FavouriteMovie>(
      model: _entities[0],
      toOneRelations: (FavouriteMovie object) => [],
      toManyRelations: (FavouriteMovie object) => {},
      getId: (FavouriteMovie object) => object.id,
      setId: (FavouriteMovie object, int id) {
        object.id = id;
      },
      objectToFB: (FavouriteMovie object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final overviewOffset = fbb.writeString(object.overview);
        final posterPathOffset = object.posterPath == null
            ? null
            : fbb.writeString(object.posterPath!);
        final backdropPathOffset = object.backdropPath == null
            ? null
            : fbb.writeString(object.backdropPath!);
        final releaseDateOffset = fbb.writeString(object.releaseDate);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.movieId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, overviewOffset);
        fbb.addOffset(4, posterPathOffset);
        fbb.addOffset(5, backdropPathOffset);
        fbb.addOffset(6, releaseDateOffset);
        fbb.addFloat64(7, object.voteAverage);
        fbb.addInt64(8, object.voteCount);
        fbb.addInt64(9, object.savedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final movieIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final overviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final posterPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final backdropPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final releaseDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final voteAverageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final voteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final savedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = FavouriteMovie(
          id: idParam,
          movieId: movieIdParam,
          title: titleParam,
          overview: overviewParam,
          posterPath: posterPathParam,
          backdropPath: backdropPathParam,
          releaseDate: releaseDateParam,
          voteAverage: voteAverageParam,
          voteCount: voteCountParam,
          savedAt: savedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FavouriteMovie] entity fields to define ObjectBox queries.
class FavouriteMovie_ {
  /// See [FavouriteMovie.id].
  static final id = obx.QueryIntegerProperty<FavouriteMovie>(
    _entities[0].properties[0],
  );

  /// See [FavouriteMovie.movieId].
  static final movieId = obx.QueryIntegerProperty<FavouriteMovie>(
    _entities[0].properties[1],
  );

  /// See [FavouriteMovie.title].
  static final title = obx.QueryStringProperty<FavouriteMovie>(
    _entities[0].properties[2],
  );

  /// See [FavouriteMovie.overview].
  static final overview = obx.QueryStringProperty<FavouriteMovie>(
    _entities[0].properties[3],
  );

  /// See [FavouriteMovie.posterPath].
  static final posterPath = obx.QueryStringProperty<FavouriteMovie>(
    _entities[0].properties[4],
  );

  /// See [FavouriteMovie.backdropPath].
  static final backdropPath = obx.QueryStringProperty<FavouriteMovie>(
    _entities[0].properties[5],
  );

  /// See [FavouriteMovie.releaseDate].
  static final releaseDate = obx.QueryStringProperty<FavouriteMovie>(
    _entities[0].properties[6],
  );

  /// See [FavouriteMovie.voteAverage].
  static final voteAverage = obx.QueryDoubleProperty<FavouriteMovie>(
    _entities[0].properties[7],
  );

  /// See [FavouriteMovie.voteCount].
  static final voteCount = obx.QueryIntegerProperty<FavouriteMovie>(
    _entities[0].properties[8],
  );

  /// See [FavouriteMovie.savedAt].
  static final savedAt = obx.QueryDateProperty<FavouriteMovie>(
    _entities[0].properties[9],
  );
}
